/**
 * Hier wird definiert, welche Icons für welche Wetterbedingungen angezeigt werden sollen.
 * 
 * @author Tim Plotzki(und der Github-Copilot)
 * @version 1.0
 */

export const iconCombinations = {
    'sunny': {
        sun: true,
        cloud: false,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'sunny windy': {
        sun: false,
        cloud: false,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: true,
        moon_wind: false,
    },
    'cloudy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: false,
        small_cloud: true,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy': {
        sun: false,
        cloud: true,
        cloud_sun: true,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'cloudy rainy' : {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: true,
        small_cloud: true,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy rainy': {
        sun: false,
        cloud: true,
        cloud_sun: true,
        rain: true,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'cloudy windy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: false,
        small_cloud: true,
        moon: false,
        cloud_moon: false,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy windy': {
        sun: false,
        cloud: true,
        cloud_sun: true,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
    'cloudy rainy windy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: true,
        small_cloud: true,
        moon: false,
        cloud_moon: false,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy rainy windy': {
        sun: false,
        cloud: true,
        cloud_sun: true,
        rain: true,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
    'clear_night': {
        sun: false,
        cloud: false,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: true,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'clear_night windy': {
        sun: false,
        cloud: false,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: false,
        wind: false,
        sunny_wind: false,
        moon_wind: true,
    },
    'partly_cloudy_night': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: true,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy_night rainy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: true,
        small_cloud: false,
        moon: false,
        cloud_moon: true,
        wind: false,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy_night windy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: false,
        small_cloud: false,
        moon: false,
        cloud_moon: true,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
    'partly_cloudy_night rainy windy': {
        sun: false,
        cloud: true,
        cloud_sun: false,
        rain: true,
        small_cloud: false,
        moon: false,
        cloud_moon: true,
        wind: true,
        sunny_wind: false,
        moon_wind: false,
    },
};